sonar.projectKey=aceest-gym
sonar.projectName=ACEest Fitness Gym
sonar.projectVersion=1.0

sonar.sources=aceest_gym
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml

sonar.language=py